use grocery_store;

-- 1️. Customer Insights
-- a.How many unique customers have placed orders?


SELECT COUNT(DISTINCT cust_id) AS Uniquecustomers FROM Orders;

-- b.Which customers have placed the highest number of orders?
SELECT cust_id,COUNT(*) AS TotalOrders FROM Orders
GROUP BY cust_id
ORDER BY TotalOrders DESC;

-- c. What is the total and average purchase value per customer?
SELECT c.cust_id, COALESCE(c.cust_name, '') AS cust_name, COUNT(*) AS TotalOrders
FROM Orders o
LEFT JOIN customers c USING (cust_id)
GROUP BY c.cust_id, c.cust_name
ORDER BY TotalOrders DESC;

-- d.What is the total and average purchase value per customer?
SELECT o.cust_id,SUM(od.total_price) AS total_purchase,
AVG(od.total_price) AS avg_purchase
FROM orders o JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.cust_id;

-- e.Who are the top 5 customers by total purchase amount?
SELECT o.cust_id,SUM(od.total_price) AS total_purchase
 FROM orders o JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.cust_id
ORDER BY total_purchase DESC LIMIT 5;

-- 2. Product Performance
-- a.How many products exist in each category? 
SELECT cat_id, COUNT(*) AS product_count
FROM products
GROUP BY cat_id;

-- b.What is the average price of products by category? 
SELECT cat_id, AVG(price) AS avg_price
FROM products
GROUP BY cat_id;

-- c. Which products have the highest total sales volume (by quantity)?
SELECT prod_id, SUM(quantity) AS total_quantity
FROM order_details
GROUP BY prod_id
ORDER BY total_quantity DESC;

-- d. What is the total revenue generated by each product?
SELECT prod_id, SUM(total_price) AS total_revenue
FROM order_details
GROUP BY prod_id
ORDER BY total_revenue DESC;

-- e. How do product sales vary by category and supplier?
SELECT p.cat_id, p.sup_id, SUM(od.total_price) AS revenue, SUM(od.quantity) AS quantity
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.cat_id, p.sup_id;

-- 3. Sales and Order Trends
-- a. How many orders have been placed in total?
SELECT COUNT(*) AS total_orders FROM orders;

-- b. What is the average value per order?
SELECT AVG(order_total.value)
FROM (
  SELECT ord_id, SUM(total_price) AS value
  FROM order_details
  GROUP BY ord_id
) AS order_total;

-- c. On which dates were the most orders placed?
SELECT order_date, COUNT(*) AS order_count
FROM orders
GROUP BY order_date
ORDER BY order_count DESC;

-- d. What are the monthly trends in order volume and revenue?
SELECT
  LEFT(order_date,7) AS month,
  COUNT(*) AS order_count,
  SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY month
ORDER BY month;

-- e. How do order patterns vary across weekdays and weekends?
SELECT
  DAYOFWEEK(order_date) AS day_of_week,
  COUNT(*) AS order_count,
  SUM(od.total_price) AS revenue
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY day_of_week;

-- 4️. Supplier Contribution
-- a. How many suppliers are there in the database?
SELECT COUNT(*) AS total_suppliers FROM supplier;

-- b. Which supplier provides the most products?
SELECT sup_id, COUNT(*) AS product_count
FROM products
GROUP BY sup_id
ORDER BY product_count DESC;

-- c. What is the average price of products from each supplier?
SELECT sup_id, AVG(price) AS avg_price
FROM products
GROUP BY sup_id;


-- d. Which suppliers contribute the most to total product sales (by revenue)?
SELECT p.sup_id, SUM(od.total_price) AS supplier_revenue
FROM products p
JOIN order_details od ON p.prod_id = od.prod_id
GROUP BY p.sup_id
ORDER BY supplier_revenue DESC;

-- 5️. Employee Performance
-- a. How many employees have processed orders?
SELECT COUNT(DISTINCT emp_id) AS employee_count
FROM orders;

-- b. Which employees have handled the most orders?
SELECT emp_id, COUNT(*) AS order_count
FROM orders
GROUP BY emp_id
ORDER BY order_count DESC;

-- c. What is the total sales value processed by each employee?
SELECT o.emp_id, SUM(od.total_price) AS total_sales
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.emp_id;

-- d. What is the average order value handled per employee?
SELECT o.emp_id, AVG(od.total_price) AS avg_order_value
FROM orders o
JOIN order_details od ON o.ord_id = od.ord_id
GROUP BY o.emp_id;

-- 6️. Order Details Deep Dive
-- a. What is the relationship between quantity ordered and total price?
SELECT quantity, AVG(total_price) AS avg_total_price
FROM order_details
GROUP BY quantity;

-- b. What is the average quantity ordered per product?
SELECT prod_id, AVG(quantity) AS avg_quantity
FROM order_details
GROUP BY prod_id;

-- c. How does the unit price vary across products and orders?
SELECT prod_id, AVG(each_price) AS avg_unit_price
FROM order_details
GROUP BY prod_id;
